# Generated by Django 4.1 on 2023-05-09 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_token_user_balance_delete_account_token_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='userType',
            field=models.CharField(choices=[('customer', 'Customer'), ('clerk', 'Clerk')], max_length=10),
        ),
    ]
