# Generated by Django 4.1 on 2023-05-12 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_token_expires'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('passed', 'Passed'), ('pending', 'Pending')], default='pending', max_length=10),
        ),
    ]
